### ISSUE TITLE
缺少 mapbox token 问题

### ISSUE THREAD

**Issue by xuanfengzu** [LeonardoSya/through-life#1]
> tsc && vite build

src/pages/map.tsx:11:23 - error TS2307: Cannot find module '../../env' or its corresponding type declarations.

11 import { token } from "../../env";
                         ~~~~~~~~~~~


Found 1 error in src/pages/map.tsx:11

 ELIFECYCLE  Command failed with exit code 2.
    Error beforeBuildCommand `pnpm build` failed with exit code 2

请问是不是在根目录下少了一个env文件之类的呀？

**Comment by LeonardoSya** [comment]
👋 你可以拉取一下最新的代码，我公开了一个public mapbox token，可以查看这个最新的提交：https://github.com/LeonardoSya/through-life/commit/d0cc995cd246dbe6c4aefec50678f917afc2c2a2  此 token 主要用于学习，请不要滥用。如果想申请自己的 mapbox token 可以通过 https://console.mapbox.com/account/access-tokens/ 了解更多
