### ISSUE TITLE
Database file request

### ISSUE THREAD

**Issue by G1nkgo7** [LeonardoSya/through-life#2]
Hi! I stumbled across your project and was very interested. I would like to ask if you can provide the database file, which can help me get started with this fun demo faster.

**Comment by LeonardoSya** [comment]
Indeed, this is currently my personal data. Soon I will provide a Vercel Postgres cloud storage solution for you to practice with.

**Comment by LeonardoSya** [comment]
I have made trajectory data deployed on Vercel Postgres available to you for learning purposes only. Please do not use it for any other purposes. Thank you for your understanding.🥳 @Gingko4ever @xleave    at this commit https://github.com/LeonardoSya/through-life/commit/041c8272954aaab75e1b798e2d9bf8e9ca0d9a93
